[package]
name = "catervas-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
catervas-core.workspace = true
catervas-protocol.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true

[lints]
workspace = true
