/** Every string the app shows (docs/SPEC.md section 10: strings externalized). */
export const en = {
	today: "Today",
	events: "Events",
	eventsForTesting: "Events (for testing)",
	settings: "Settings",
	noPage: "No page here",
	noPageHome: "Go to the start page",
	linkUsed:
		"This start link was already used. Each link works once, so run farik serve again for a new one.",
	noSessionTitle: "Open Farik from its start link",
	noSessionBody:
		"For your safety, this page only works when opened from the link Farik gives you. Each link works once, so an old one from your history will not open it.",
	lostTitle: "Farik stopped answering",
	lostBody:
		"Your team is safe. Nothing is lost while this page waits. If you closed the Farik window on your computer, start it again and this page reconnects by itself.",
	lostRetry: "Trying again in 5 seconds",
	stepTerminal: "Open the Terminal app on your computer.",
	stepType: "Type this and press Enter:",
	stepOpen:
		"Farik prints a link that starts with http://127.0.0.1. Open it in this browser.",
	desktopLater: "The desktop app, coming later, will skip these steps.",
	copy: "Copy",
	brand: "Farik",
	navRail: "Main",
	navBar: "Places",
	connected: "Connected",
	connecting: "Connecting",
	teamWorking: "The team is working",
	teamPaused: "The team is paused",
	pauseTeam: "Pause the team",
	resumeTeam: "Resume the team",
	pause: "Pause",
	resume: "Resume",
	pausedLead: "The team is paused.",
	pausedNothingNew: "Nothing new starts until you resume.",
	pausedStillYours: "You can still answer, approve and accept.",
	eventsCaption: "The last 100 events, newest first",
	eventSeq: "Seq",
	eventTime: "Time",
	eventKind: "Kind",
	eventTask: "Task",
	theme: "Theme",
	themeLight: "Light",
	themeLightNote: "Sand pages. The default.",
	themeDark: "Dark",
	themeDarkNote: "Midnight pages, easier at night.",
	themeSystem: "Match my computer",
	themeSystemNote: "Follows your computer’s setting.",
	advanced: "Advanced settings",
	advancedSwitch: "Show advanced settings",
	advancedBody:
		"Farik’s defaults are safe, and you never need to change them. Turning this on shows the detailed settings in each screen: what each agent may do, the team’s rules, the list of checks Farik can run, the models, and how Farik judges a plan ready.",
	advancedSafe:
		"Farik refuses any change that would leave your team unable to work, and says what to change instead.",
	thisComputer: "Farik on this computer",
	connectedLead: "Connected.",
	connectedBody:
		"This page talks to Farik running on your computer, and nothing leaves it except the requests to the AI models.",
	projectFolder: "Project folder",
	address: "Address",
	disconnect: "Disconnect this browser",
	language: "Language",
	english: "English",
	englishOnly: "English only for now. More languages come later.",
	setupTag: "AI HARNESS ENGINE",
	loopPlan: "Plan.",
	loopBuild: "Build.",
	loopIterate: "Iterate.",
	loopShip: "Ship together.",
	setupSteps: "Setup steps",
	wizardComputer: "Your computer",
	wizardAccount: "Your AI account",
	wizardProject: "Your project",
	wizardFound: "What we found",
	wizardTeam: "Your team",
	wizardMay: "What they may do",
	wizardSpending: "Spending",
	wizardFinishing: "Finishing work",
	back: "Back",
	continue: "Continue",
	computerTitle: "Checking your computer",
	computerLead:
		"Farik needs three programs. It looked for each one and changed nothing.",
	computerClaude: "Claude Code, which your agents run in",
	computerGit: "git, which keeps your project’s history",
	computerDocker: "Docker, which keeps your agents’ commands in a safe box",
	computerImage: "The safe box itself, which Farik prepares in Docker",
	checking: "Looking…",
	ready: "Ready",
	notFound: "Not found",
	tooOld: "Too old",
	notRunning: "Not running",
	versionFound: "Version {version} found.",
	claudeMissing:
		"Install Claude Code from claude.com/claude-code, then press Check again.",
	claudeTooOld:
		"Farik needs a newer Claude Code. Type claude update in the Terminal, then press Check again.",
	gitMissing: "Install git from git-scm.com, then press Check again.",
	dockerMissing:
		"Install Docker Desktop from docker.com, start it, then press Check again.",
	dockerNotRunning:
		"Docker is installed but not running. Start Docker Desktop, then press Check again.",
	dockerOrWithout:
		"Or continue without it: your agents’ commands then run directly on this computer.",
	imageMissing: "Farik prepares it once. It takes a few minutes.",
	prepare: "Prepare it",
	noDockerWarning:
		"Without Docker, a mistaken or tricked agent command can reach any file you can. Farik reminds you of this every time it starts.",
	checkAgain: "Check again",
	continueWithoutDocker: "Continue without Docker",
	accountTitle: "Connect your AI account",
	accountLead:
		"Your agents think with Claude, and your account pays for it. Farik keeps the key safely on this computer and never shows it to an agent.",
	accountKind: "Your Claude account",
	subscription: "I have a Claude subscription (Pro or Max)",
	subscriptionNote:
		"Recommended if you already pay for Claude. Make a key for Farik in two steps:",
	subscriptionStepType: "Open the Terminal and type",
	subscriptionStepPaste:
		"Sign in when your browser opens, then paste the key it prints here.",
	subscriptionKey: "Your subscription key",
	subscriptionHint: "It starts with sk-ant-oat.",
	apiKey: "I have an API key",
	apiKeyNote: "From console.anthropic.com. You pay for what your agents use.",
	apiKeyField: "Your API key",
	apiKeyHint: "It starts with sk-ant-api.",
	saveContinue: "Save and continue",
	storedKeychain: "Your key is saved in your computer’s keychain.",
	storedFile:
		"Your key is saved in a private file on this computer, because it has no keychain Farik can use.",
	accountFound: "Farik already has your key. You can go on.",
	projectTitle: "Is this for a project you already have?",
	projectLead:
		"Farik works inside a folder on this computer. Your team keeps its plans and notes there, next to your work.",
	projectChoice: "Project",
	projectExisting: "Yes, I have a project folder",
	projectExistingNote:
		"Pick the folder. It needs to be a git repository, which most code projects already are.",
	projectNew: "No, start a new one",
	projectNewNote:
		"Tell the team what you want to make, in a few sentences. Farik makes a new folder for it.",
	newWhat: "What do you want to make?",
	newWhatHint:
		"For example: an ordering site for my bakery, where customers pick up in the morning. At least 20 characters.",
	newName: "What should the project be called?",
	newNameHint: "Farik makes the folder {folder}.",
	newWhere: "Where should the folder go?",
	choose: "Choose",
	browserTitle: "Choose your project folder",
	browserParentTitle: "Choose where the new folder goes",
	browserLead:
		"These are the folders in your home folder. Farik only looks at folder names here.",
	folders: "Folders",
	home: "Home",
	upOne: ".. (up one folder)",
	gitProject: "git project",
	notGitProject: "not a git project",
	noFolders: "There are no folders here.",
	selected: "Selected:",
	openFolder: "Open folder",
	useFolder: "Use this folder",
	browserNote:
		"A folder that is not a git project can’t be used yet. For a new project, go back and choose “No, start a new one”: Farik makes the folder and sets up git for you.",
	opening: "Opening your project…",
	takeOnError: "Farik could not open that project.",
	scanTitle: "Here is what Farik found in your project",
	scanLead:
		"Farik read the folder without changing anything. Your team starts from this, so tell us if something is wrong.",
	scanFound: "What Farik found",
	scanWhat: "What it is",
	scanTested: "How it is tested",
	scanChecked: "How it is checked",
	scanLast: "Last change",
	scanPrivate: "Kept private",
	scanWorkspace: "a workspace of {count} packages",
	scanUnknown: "Farik could not tell",
	scanTestsIn: "Tests in {location}",
	scanNoTests: "No tests found",
	scanNoChecks: "No checks found",
	scanNoCommits: "No changes yet",
	scanPrivateNote: "No agent will ever open them.",
	scanNothingPrivate: "Nothing private found",
	scanChecksNote:
		"The checks found become your first checks. Farik runs them itself on every piece of work before it reaches you.",
	scanWrong: "Something is wrong",
	scanWrongField: "What is wrong?",
	scanWrongHint:
		"Your team reads this before it starts, for example: it is a shop, not a game.",
	scanWrongSave: "Tell the team",
	scanWrongSaved: "Saved. Your team reads it before it starts.",
	scanRight: "That's right",
	teamTitle: "Who should be on your team?",
	teamLead:
		"We suggest five, one for each job. You can rename them and change their pictures now or later. To add a second developer, choose “Add someone”.",
	teamMembers: "Your team",
	teamInclude: "Include {role}",
	teamName: "Name for the {role}",
	teamAdd: "Add someone",
	teamContinueFive: "Continue with these five",
	teamContinue: "Continue with this team",
	roleProductManager: "Product Manager",
	roleScrumMaster: "Scrum Master",
	roleArchitect: "Architect",
	roleDeveloper: "Developer",
	roleMarketing: "Marketing Specialist",
	mayTitle: "What may your team do on its own?",
	mayLead:
		"Two things can cause real harm, so Farik asks you about them directly. Nothing runs until you answer both.",
	mayCommands: "May the team run commands on this computer?",
	mayCommandsNote:
		"Running the tests and trying the app needs this. Commands run in a sealed box, away from your other files.",
	mayCommandsYes: "Yes, the Developer and Architect may",
	mayCommandsYesNote:
		"Recommended. Without it nobody can check that the code works.",
	mayCommandsNo: "No, nobody may",
	mayCommandsNoNote: "The team can plan and write, but cannot test anything.",
	mayStillChecks:
		"Farik still runs every check itself; the agents cannot run commands.",
	mayPush: "May the Developer send its work to your online repository?",
	mayPushNoteOne:
		"Only {name}, the Developer, ever sends code, and only to its own fix or feature branch. Farik sends the other agents’ documents itself. Nothing reaches your main branch without you.",
	mayPushNoteMany:
		"Only the Developers ever send code, and only to their own fix or feature branches. Farik sends the other agents’ documents itself. Nothing reaches your main branch without you.",
	mayPushYes: "Yes, on its own branches",
	mayPushYesNote: "Useful if you review work on GitHub.",
	mayPushNo: "No, keep everything on this computer",
	mayPushNoNote: "The safer choice. You can change it later in Team.",
	mayAlready: "What each agent may do already",
	mayAnswerBoth: "Answer both questions to continue.",
	spendTitle: "Do you want a daily spending limit?",
	spendLead:
		"Each agent uses an AI model, and each piece of work costs a little. You can set a limit, or leave it open and watch costs on the Costs page.",
	spendChoice: "Daily spending limit",
	spendNone: "No limit",
	spendNoneNote:
		"The team keeps working until the work is done. Best if you pay a flat monthly subscription for your AI model.",
	spendDaily: "Stop the team after a set amount each day",
	spendDailyNote:
		"When the team reaches the limit, everyone pauses and you get a message. They carry on the next day, or sooner if you raise the limit.",
	spendAmount: "Limit per day, in US dollars",
	spendAmountWrong: "Enter an amount above zero, such as 10.",
	spendFixed:
		"Some limits are always on, whatever you choose. No agent works on one thing for more than 30 minutes at a time, and a piece of work sent back three times comes to you.",
	firstDay:
		"A first full day for a team of five costs under twenty dollars on your own key at today’s prices.",
	finishTitle: "When you accept a piece of work, what happens to it?",
	finishLead:
		"Accepted work has to be added to your project. Choose how much you want to do by hand.",
	finishChoice: "Accepted work",
	finishAuto: "Farik adds it for me",
	finishAutoNote:
		"Recommended. Farik adds the work to your project as soon as you accept it, and sends it to your online repository if you have one.",
	finishPullRequest: "Open a pull request on GitHub for each piece",
	finishPullRequestNote:
		"You, or someone you trust, merges each one on GitHub. Needs the GitHub app on this computer.",
	finishManual: "I will add each one myself",
	finishManualNote:
		"Farik waits. Each accepted piece shows an “Add to project” button until you press it.",
	finishSafe:
		"Rules for the whole team, the checks every piece of work must pass, and how plans are judged are already set to safe choices.",
	startTeam: "Start the team",
	advancedHide: "Hide advanced settings",
	advancedLead:
		"These are already set to safe choices. Change them only if you want to. You can come back to them any time in Settings.",
	rulesTitle: "Team rules",
	rulesLead: "Rules every agent follows, and that no agent can change.",
	editAsText: "Edit as text",
	rulesText: "Team rules, as text",
	rulesTextUse: "Use this text",
	rulesTextWrong: "This is not a set of team rules: {why}",
	rulePrivate: "Keep private files private",
	rulePrivateNote:
		"No agent may open passwords and keys: .env files, and key files.",
	ruleTests: "Every code change comes with new tests",
	ruleTestsNote:
		"A plan for code is not ready until it asks for tests of the change.",
	ruleDeveloper: "Only the Developer changes code",
	ruleDeveloperNote: "Everyone else may only change documents and plans.",
	ruleMaxCost: "Most one piece of work may cost",
	ruleMaxCostHint: "In US dollars. Leave it empty for no limit.",
	alwaysOn: "Always on",
	checksTitle: "Checks for every piece of work",
	checksLead: "Farik runs these itself before work reaches you.",
	checkFound: "Found in your project. Runs: {command}",
	checkYours: "Added by you.",
	checkReviewed: "Someone on the team reviewed it",
	checkReviewedNote: "Another agent reads the work before you see it.",
	checkNew: "A new check",
	checkNewHint:
		"Say what must be true of finished work, in at least 10 characters. Another agent checks it.",
	checkAdd: "Add a check",
	planTitle: "Checking plans",
	planLead: "Before anyone starts, one agent checks that the plan makes sense.",
	planRequired: "Check every plan before work starts",
	planQuestions: "What the checker asks about each plan",
	planBudget: "Can this be done within its budget?",
	planBudgetNote: "So work does not stop halfway because the money ran out.",
	planNotice: "Would the checks notice if it went wrong?",
	planNoticeNote: "So a broken result cannot pass as finished.",
	planSmall: "Is it small enough to finish in one go?",
	planSmallNote: "Big plans get split into smaller pieces first.",
	planJudge: "Who checks",
	planJudgeAuto: "Farik chooses: {who}",
	planJudgeNamed: "{name}, the {role}",
	planJudgeNone: "The {role}, once the team has one",
	team: "Team",
	teamPageLead:
		"{count} agents work on {name}. A team needs a Product Manager and a Developer; everyone else is up to you. You can have up to seven.",
	agentEditLink: "Edit {name}",
	agentPause: "Pause {name}",
	agentResume: "Resume {name}",
	agentActive: "On the team",
	agentPaused: "Paused",
	agentModel: "Model",
	agentModelRole: "The role’s model",
	teamChangesTitle: "Pause, retire or replace",
	teamChangesBody:
		"Pausing stops an agent from taking new work; it finishes nothing halfway. Retiring removes it from the team but keeps what it learned in your project, so whoever replaces it can read it. Changes start with the agent’s next piece of work, never in the middle of one.",
	teamCostTitle: "What a team like this costs",
	teamCostNote: "It is a guide, not a limit.",
	agentBack: "Back to your team",
	agentTitle: "{name}, your {role}",
	agentMissing: "There is no agent called {id} on your team.",
	agentName: "Name",
	agentTalks: "How {name} talks",
	agentTalksHint:
		"One line. It shapes {name}’s messages in the channel, not the quality of the work.",
	agentEffort: "How carefully {name} works",
	effortLow: "Quick",
	effortLowNote: "Cheaper, for simple jobs",
	effortMedium: "Balanced",
	effortMediumNote: "Good for most work",
	effortHigh: "Careful",
	effortHighNote: "Thinks longest; costs most",
	agentMay: "What {name} may do",
	agentMayAdvanced: "Turn on Advanced to see each permission.",
	tierRead: "Read the project",
	tierReadNote: "Every agent can.",
	tierWrite: "Change files in its task",
	tierWriteNote: "Only the files the plan allows.",
	tierExecute: "Run commands",
	tierExecuteNote: "Inside a safe box on your computer.",
	tierGitLocal: "Save its work on its own branch",
	tierGitLocalNote: "Never on your main branch.",
	tierNetwork: "Use the internet",
	tierNetworkNote: "Looks things up and reads web pages.",
	tierGitRemote: "Push to GitHub and open pull requests",
	tierGitRemoteNote: "Nobody has this until you give it.",
	tierExternal: "Do things outside your computer",
	tierExternalNote: "Sending mail, posting, deploying. You approve each one.",
	agentDefaults: "Put back the role’s defaults",
	agentEffects: "What this changes",
	agentPlace: "{name}’s place on the team",
	agentPauseNote:
		"{name} finishes nothing halfway and takes no new work until you resume.",
	agentReplace: "Replace {name}",
	agentReplaceNote: "A new {role} joins and starts from what {name} learned.",
	agentRetire: "Retire {name}",
	agentRetireNote:
		"{name} leaves the team. What {name} learned stays in your project for whoever comes next.",
	agentSave: "Save changes",
	agentCancel: "Cancel",
	agentNextWork: "Changes start with {name}’s next piece of work.",
	accountRow: "Your AI account",
	accountConnected: "Claude, with {kind}.",
	accountApiKey: "an API key",
	accountSubscription: "your Claude subscription",
	accountKeychain: "Kept in your computer’s keychain.",
	accountFile: "Kept in a private file on this computer.",
	accountEnvironment: "Read from this computer’s environment.",
	accountNone: "No AI account is connected.",
	accountDisconnect: "Disconnect this account",
	accountGone:
		"Disconnected. The team is paused; start Farik again to connect another account.",
	accountKept:
		"Farik reads this key from the {variable} variable on this computer, so it cannot remove it. Remove it there, then start Farik again.",
	statusPlanning: "Planning",
	statusToDo: "To do",
	statusInProgress: "In progress",
	statusReworked: "Being reworked",
	statusReview: "Review",
	statusDone: "Done",
	statusStuck: "Stuck",
	statusWaiting: "Waiting on you",
	statusHelp: "Needs your help",
	statusCancelled: "Cancelled",
	teamBand: "Your team",
	sprintLine: "Sprint {n} is running: {done} of {total} tasks done",
	requestLabel: "What should the team do next?",
	requestHint:
		"{name} reads every request and asks you if anything is unclear.",
	requestSend: "Send to the team",
	requestTooShort:
		"Say a little more about what you want the team to do: at least 20 characters.",
	waitingTitle: "Waiting on you ({count})",
	waitingList: "Waiting on you",
	waitingNone: "Nothing waits on you.",
	waitingApproval: "Approve the plan for {title}",
	waitingAcceptance: "Accept {title}",
	waitingQuestion: "{agent} has a question",
	waitingHelp: "{agent} needs your help",
	waitingIntegration: "Add {title} to your project",
	waitingReview: "Review",
	waitingAnswer: "Answer",
	waitingHelpButton: "Help",
	waitingAdd: "Add",
	checksPassed: "All {count} of Farik’s checks passed.",
	movedTitle: "What moved since yesterday",
	movedNone: "Nothing moved since yesterday.",
	backToToday: "Back to Today",
	requestTitle: "Your request is with the team",
	requestSent: "{id}, sent at {time} UTC.",
	youAsked: "You asked",
	sizing: "{name} is sizing your request…",
	sizedAs: "{name} sized it as {size}",
	youSizedAs: "You sized it as {size}",
	sizeLarge: "a big request",
	sizeSmall: "a small request",
	decided: "{name}, your {role}, decided",
	sizeLargeCard: "A big request",
	sizeLargeBody:
		"{pm} writes a plan with parts, asks you what is needed, and waits for your approval before anyone starts building.",
	sizeSmallCard: "A small request",
	sizeSmallBody:
		"One task, planned and built straight away. Choose this if you only want a first, simple version.",
	sizeChosen: "This is what {name} chose.",
	sizeChosenByYou: "This is what you chose.",
	resizeToSmall: "Change this to a small request",
	resizeToLarge: "Change this to a big request",
	resizeReason: "Changed by you",
	nextTitle: "What happens next",
	nextLarge1: "{pm} asks you a few questions. You will see them on Today.",
	nextLarge2: "{pm} writes the plan and Farik checks it is complete.",
	nextLarge3: "You approve the plan, or ask for changes.",
	nextLarge4: "{breaker} splits it into tasks and the team starts.",
	nextSmall1:
		"{pm} asks you anything that is unclear. You will see it on Today.",
	nextSmall2: "{pm} writes the plan and Farik checks it is complete.",
	nextSmall3: "The team builds it, and a teammate reviews the work.",
	nextSmall4: "You accept the work, or send it back with a note.",
	aboutRequest: "About this request",
	aboutSent: "Sent",
	aboutSizedBy: "Sized by",
	aboutPlannedBy: "Planned by",
	aboutPlanId: "Plan id",
	aboutStatus: "Status",
	nameRole: "{name}, {role}",
	you: "You",
	notYet: "Not yet",
	questionsTitle: "{agent}’s questions",
	questionsLead:
		"Plan {id}. {agent} asks before writing the plan, so the plan matches what you want.",
	questionsNone: "There are no questions for {id}.",
	youAnswered: "You answered:",
	answered: "Answered",
	laterQuestion: "{agent} shows this once you answer question {n}.",
	suggests: "{agent} suggests",
	ownWordsMany: "Or say it in your own words",
	ownWordsOne: "Or answer in your own words",
	sendAnswer: "Send answer",
	letDecide: "Let {agent} decide",
	decideText: "Decide as you think best, and say what you chose.",
	oneQuestionTitle: "{agent} has a question",
	oneQuestionLead: "About {id}. {agent} stopped until you answer.",
	asks: "{agent}, your {role}, asks",
	aboutQuestions: "About questions",
	aboutQuestionsBody:
		"A question is not a problem. {agent} just needs your answer to carry on.",
	aboutQuestionsNext: "Your answer goes straight into {agent}’s next session.",
	approveTitle: "Approve the plan for {title}",
	approveLead: "Plan {id}.",
	approveLeadEpic:
		"Plan {id}. Every plan with parts waits for your approval before anyone builds it.",
	planSigned: "{name}, your Product Manager, wrote this for you",
	planParts: "The plan in {n} parts",
	planPartsHint: "The line under each part is how Farik will know it is done.",
	planDoneWhen: "Done when {text}",
	planWholeDoneWhen: "The whole plan is done when",
	planOut: "Not in this plan",
	planChecked: "What Farik checked",
	planCheckedAll:
		"The plan is complete enough for the team to start. Farik checks this itself.",
	checkPassed: "Passed",
	checkNotYet: "Not yet",
	planWritten: "See the plan as written",
	planAbout: "About this plan",
	approveQuestions: "Questions",
	planAnswered: "{n} answered",
	planRisk: "Risk",
	riskLow: "Low",
	riskMedium: "Medium",
	riskHigh: "High",
	planEstimate: "Estimate",
	planBuilders: "Builders",
	planEdit: "Edit the plan yourself",
	planApprove: "Approve the plan",
	planAskChanges: "Ask for changes",
	planApproveNote:
		"Approving lets {breaker} split the plan into tasks for the team.",
	planAskTitle: "Ask {pm} for changes",
	planAskNote: "What should change?",
	planAskSend: "Send it back",
	editTitle: "Edit the plan for {title}",
	editBack: "Back to the plan",
	editAdvanced: "Advanced view",
	lockOpen: "{pm} can still change this plan",
	lockOpenHint: "Lock it so that only you change it.",
	lockButton: "Lock the plan",
	lockClosed: "You have locked this plan",
	lockClosedHint: "{pm} cannot change it until you unlock it.",
	unlockButton: "Unlock",
	holdTitle: "The team is working to this plan",
	holdHint:
		"To change it, hold the work first. The task then waits for you until you save.",
	holdButton: "Hold the work",
	holdReason: "Held by you to change the plan",
	fieldIntent: "Why you want it",
	fieldIntentHint: "Says why, from the customer’s side.",
	fieldSummary: "The summary you read first",
	fieldParts: "The parts of the plan",
	fieldPart: "Part {n}",
	addPart: "Add a part",
	fieldCriteria: "How we will know it is done",
	fieldCriteriaHint: "Each check says how it is checked.",
	fieldCriterion: "Check {n}",
	criterionWho: "Who checks it",
	criterionReview: "Someone on the team reviews it",
	criterionHuman: "You decide",
	criterionCommand: "Farik runs a command",
	criterionCommandField: "The command",
	criterionCommandLocked:
		"Farik runs a command. Turn on Advanced view to change it.",
	addCriterion: "Add a check",
	fieldOut: "What is left out",
	fieldOutHint:
		"One per line. Name at least one thing this plan does not do. It keeps the work from growing.",
	fieldBudget: "Spending limit in dollars",
	fieldRisk: "How risky it is",
	fieldPaths: "Files the team may change",
	fieldPathsHint: "One per line. Inside the paths your team rules allow.",
	verdictTitle: "Ready to approve?",
	verdictCount: "{n} of {total} checks pass.",
	verdictOne: "The one left: {plain}",
	verdictMany: "Still to do:",
	verdictNote:
		"Farik checks the plan as you type. The results come from your project, not from this page.",
	editSave: "Save",
	savedBack:
		"Saved. {pm} checks the plan again, then it comes back to you to approve.",
	saved: "Saved.",
	gateTitle: "Accept {title}",
	gateWrote: "{name}, your {role}, wrote this for you",
	gateReviewed: "{name}, your {role}, reviewed it",
	gateCheckedHint:
		"Farik ran these checks itself. It did not take the team’s word for them.",
	gateSeeChanges: "See the code changes",
	gateHideChanges: "Hide the code changes",
	gateSize: "{n} files, +{added} −{removed}",
	gateSizeOne: "1 file, +{added} −{removed}",
	gateChanges: "The code changes",
	gateAbout: "About this task",
	gatePlanApproved: "Plan approved",
	gateTries: "Tries",
	triesOf: "{used} of {allowed}",
	gateCost: "Cost",
	gateHistory: "See the whole history",
	gateWhatChecked: "What you checked",
	gateAccept: "Accept the work",
	gateSendBack: "Send back with a note",
	gateAdd: "Add to project",
	sendBackTitle: "Send {title} back to {name}",
	sendBackWhat: "What is not right? Choose any that apply.",
	sendBackElse: "Something else",
	sendBackNote: "Your note to {name}",
	sendBackTry:
		"This is try {used} of {allowed}. After the last, Farik stops and asks you.",
	sendBackCancel: "Cancel",
	sendBackSend: "Send back to {name}",
	helpTitle: "{name} needs your help with “{title}”",
	helpExplains: "{name}, your {role}, explains what happened",
	helpTried: "What {name} tried",
	helpNow: "What should happen now?",
	helpNote: "A note for {name} (optional)",
	helpWaiting: "Waiting since",
	helpSpent: "Spent",
	helpSpentOf: "{spent} of {max}",
	helpReviewer: "Reviewer",
	refuseTooMany:
		"A team has seven people at most. Retire someone before adding another.",
	refuseNeedsProductManager:
		"Your team needs a Product Manager to write its plans. Include one.",
	refuseNeedsDeveloper:
		"Your team needs a Developer to do the work. Include one.",
	refuseRepeatedId: "Two people on the team have the same name. Rename one.",
	refuseWorked:
		"Someone you took off the team has already done work. Retire them from their card instead.",
	refuseName: "Give everyone a name.",
	refuseKeepsRead:
		"Every agent reads the project. Pause the agent instead of taking reading away.",
	refuseStatusFromCard: "Pause, retire or resume someone from their card.",
	refuseJudge:
		"Nobody on the team is an active {role}. Let Farik choose who checks, or add a {role}.",
	refuseNoQuestions:
		"Checking plans needs at least one question. Tick one, or stop checking plans.",
	refuseQuestionLength: "A question is 10 to 200 characters long.",
	refuseLastOfRole: "{name} is your only {role}, so add another {role} first.",
	refuseLastJudge:
		"{name} checks your plans. Let Farik choose who checks, or add another {role}, first.",
	refuseOther:
		"Farik could not make this change. Check what you changed, then try again.",
	teamAddRole: "Their role",
	teamFull:
		"Your team has seven people, the most it can have. Retire someone to make room.",
	mayRead: "reads the project",
	mayWrite: "changes the files of its task",
	mayExecute: "runs commands in a sealed box",
	mayGitLocal: "saves its work on its own branch",
	mayNetwork: "looks things up on the web",
	mayGitRemote: "sends its work to its own branches online",
	mayExternal: "acts outside your computer, with your approval",
	putBack: "Put back the default",
};
