/** Every string the app shows (docs/SPEC.md section 10: strings externalized). */
export const en = {
	events: "Events",
	settings: "Settings",
	noPage: "No page here",
	noPageHome: "Go to the start page",
	linkUsed:
		"This start link was already used. Each link works once, so run farik serve again for a new one.",
	noSessionTitle: "Open Farik from its start link",
	noSessionBody:
		"For your safety, this page only works when opened from the link Farik gives you. Each link works once, so an old one from your history will not open it.",
	lostTitle: "Farik stopped answering",
	lostBody:
		"Your team is safe. Nothing is lost while this page waits. If you closed the Farik window on your computer, start it again and this page reconnects by itself.",
	lostRetry: "Trying again in 5 seconds",
	stepTerminal: "Open the Terminal app on your computer.",
	stepType: "Type this and press Enter:",
	stepOpen:
		"Farik prints a link that starts with http://127.0.0.1. Open it in this browser.",
	desktopLater: "The desktop app, coming later, will skip these steps.",
	copy: "Copy",
	brand: "Farik",
	navRail: "Main",
	navBar: "Places",
	connected: "Connected",
	connecting: "Connecting",
	teamWorking: "The team is working",
	teamPaused: "The team is paused",
	pauseTeam: "Pause the team",
	resumeTeam: "Resume the team",
	pause: "Pause",
	resume: "Resume",
	pausedLead: "The team is paused.",
	pausedNothingNew: "Nothing new starts until you resume.",
	pausedStillYours: "You can still answer, approve and accept.",
	eventsCaption: "The last 100 events, newest first",
	eventSeq: "Seq",
	eventTime: "Time",
	eventKind: "Kind",
	eventTask: "Task",
	theme: "Theme",
	themeLight: "Light",
	themeLightNote: "Sand pages. The default.",
	themeDark: "Dark",
	themeDarkNote: "Midnight pages, easier at night.",
	themeSystem: "Match my computer",
	themeSystemNote: "Follows your computer’s setting.",
	advanced: "Advanced settings",
	advancedSwitch: "Show advanced settings",
	advancedBody:
		"Farik’s defaults are safe, and you never need to change them. Turning this on shows the detailed settings in each screen: what each agent may do, the team’s rules, the list of checks Farik can run, the models, and how Farik judges a plan ready.",
	advancedSafe:
		"Farik refuses any change that would leave your team unable to work, and says what to change instead.",
	thisComputer: "Farik on this computer",
	connectedLead: "Connected.",
	connectedBody:
		"This page talks to Farik running on your computer, and nothing leaves it except the requests to the AI models.",
	projectFolder: "Project folder",
	address: "Address",
	disconnect: "Disconnect this browser",
	language: "Language",
	english: "English",
	englishOnly: "English only for now. More languages come later.",
};
