/** Every string the app shows (docs/SPEC.md section 10: strings externalized). */
export const en = {
	today: "Today",
	events: "Events",
	eventsForTesting: "Events (for testing)",
	settings: "Settings",
	noPage: "No page here",
	noPageHome: "Go to the start page",
	linkUsed:
		"This start link was already used. Each link works once, so run farik serve again for a new one.",
	noSessionTitle: "Open Farik from its start link",
	noSessionBody:
		"For your safety, this page only works when opened from the link Farik gives you. Each link works once, so an old one from your history will not open it.",
	lostTitle: "Farik stopped answering",
	lostBody:
		"Your team is safe. Nothing is lost while this page waits. If you closed the Farik window on your computer, start it again and this page reconnects by itself.",
	lostRetry: "Trying again in 5 seconds",
	stepTerminal: "Open the Terminal app on your computer.",
	stepType: "Type this and press Enter:",
	stepOpen:
		"Farik prints a link that starts with http://127.0.0.1. Open it in this browser.",
	desktopLater: "The desktop app, coming later, will skip these steps.",
	copy: "Copy",
	brand: "Farik",
	navRail: "Main",
	navBar: "Places",
	connected: "Connected",
	connecting: "Connecting",
	teamWorking: "The team is working",
	teamPaused: "The team is paused",
	pauseTeam: "Pause the team",
	resumeTeam: "Resume the team",
	pause: "Pause",
	resume: "Resume",
	pausedLead: "The team is paused.",
	pausedNothingNew: "Nothing new starts until you resume.",
	pausedStillYours: "You can still answer, approve and accept.",
	eventsCaption: "The last 100 events, newest first",
	eventSeq: "Seq",
	eventTime: "Time",
	eventKind: "Kind",
	eventTask: "Task",
	theme: "Theme",
	themeLight: "Light",
	themeLightNote: "Sand pages. The default.",
	themeDark: "Dark",
	themeDarkNote: "Midnight pages, easier at night.",
	themeSystem: "Match my computer",
	themeSystemNote: "Follows your computer’s setting.",
	advanced: "Advanced settings",
	advancedSwitch: "Show advanced settings",
	advancedBody:
		"Farik’s defaults are safe, and you never need to change them. Turning this on shows the detailed settings in each screen: what each agent may do, the team’s rules, the list of checks Farik can run, the models, and how Farik judges a plan ready.",
	advancedSafe:
		"Farik refuses any change that would leave your team unable to work, and says what to change instead.",
	thisComputer: "Farik on this computer",
	connectedLead: "Connected.",
	connectedBody:
		"This page talks to Farik running on your computer, and nothing leaves it except the requests to the AI models.",
	projectFolder: "Project folder",
	address: "Address",
	disconnect: "Disconnect this browser",
	language: "Language",
	english: "English",
	englishOnly: "English only for now. More languages come later.",
	setupTag: "AI HARNESS ENGINE",
	loopPlan: "Plan.",
	loopBuild: "Build.",
	loopIterate: "Iterate.",
	loopShip: "Ship together.",
	setupSteps: "Setup steps",
	wizardComputer: "Your computer",
	wizardAccount: "Your AI account",
	wizardProject: "Your project",
	wizardFound: "What we found",
	wizardTeam: "Your team",
	wizardMay: "What they may do",
	wizardSpending: "Spending",
	wizardFinishing: "Finishing work",
	back: "Back",
	continue: "Continue",
	computerTitle: "Checking your computer",
	computerLead:
		"Farik needs three programs. It looked for each one and changed nothing.",
	computerClaude: "Claude Code, which your agents run in",
	computerGit: "git, which keeps your project’s history",
	computerDocker: "Docker, which keeps your agents’ commands in a safe box",
	computerImage: "The safe box itself, which Farik prepares in Docker",
	checking: "Looking…",
	ready: "Ready",
	notFound: "Not found",
	tooOld: "Too old",
	notRunning: "Not running",
	versionFound: "Version {version} found.",
	claudeMissing:
		"Install Claude Code from claude.com/claude-code, then press Check again.",
	claudeTooOld:
		"Farik needs a newer Claude Code. Type claude update in the Terminal, then press Check again.",
	gitMissing: "Install git from git-scm.com, then press Check again.",
	dockerMissing:
		"Install Docker Desktop from docker.com, start it, then press Check again.",
	dockerNotRunning:
		"Docker is installed but not running. Start Docker Desktop, then press Check again.",
	dockerOrWithout:
		"Or continue without it: your agents’ commands then run directly on this computer.",
	imageMissing: "Farik prepares it once. It takes a few minutes.",
	prepare: "Prepare it",
	computerBrowser: "Browser for the UI/UX Designer",
	browserMissing:
		"Your UI/UX Designer opens your app in this browser, inside the safe box. Farik fetches it once. It takes a few minutes.",
	fetchIt: "Fetch it",
	noDockerWarning:
		"Without Docker, a mistaken or tricked agent command can reach any file you can, and the keys you gave your agents’ connectors. Farik reminds you of this every time it starts.",
	checkAgain: "Check again",
	continueWithoutDocker: "Continue without Docker",
	accountTitle: "Connect your AI account",
	accountLead:
		"Your agents think with Claude, and your account pays for it. Farik keeps the key safely on this computer and never shows it to an agent.",
	accountKind: "Your Claude account",
	subscription: "I have a Claude subscription (Pro or Max)",
	subscriptionNote:
		"Recommended if you already pay for Claude. Make a key for Farik in two steps:",
	subscriptionStepType: "Open the Terminal and type",
	subscriptionStepPaste:
		"Sign in when your browser opens, then paste the key it prints here.",
	subscriptionKey: "Your subscription key",
	subscriptionHint: "It starts with sk-ant-oat.",
	apiKey: "I have an API key",
	apiKeyNote: "From console.anthropic.com. You pay for what your agents use.",
	apiKeyField: "Your API key",
	apiKeyHint: "It starts with sk-ant-api.",
	saveContinue: "Save and continue",
	storedKeychain: "Your key is saved in your computer’s keychain.",
	storedFile:
		"Your key is saved in a private file on this computer, because it has no keychain Farik can use.",
	accountFound: "Farik already has your key. You can go on.",
	projectTitle: "Is this for a project you already have?",
	projectLead:
		"Farik works inside a folder on this computer. Your team keeps its plans and notes there, next to your work.",
	projectChoice: "Project",
	projectExisting: "Yes, I have a project folder",
	projectExistingNote:
		"Pick the folder. It needs to be a git repository, which most code projects already are.",
	projectNew: "No, start a new one",
	projectNewNote:
		"Tell the team what you want to make, in a few sentences. Farik makes a new folder for it.",
	newWhat: "What do you want to make?",
	newWhatHint:
		"For example: an ordering site for my bakery, where customers pick up in the morning. At least 20 characters.",
	newName: "What should the project be called?",
	newNameHint: "Farik makes the folder {folder}.",
	newWhere: "Where should the folder go?",
	choose: "Choose",
	browserTitle: "Choose your project folder",
	browserParentTitle: "Choose where the new folder goes",
	browserLead:
		"These are the folders in your home folder. Farik only looks at folder names here.",
	folders: "Folders",
	home: "Home",
	upOne: ".. (up one folder)",
	gitProject: "git project",
	notGitProject: "not a git project",
	noFolders: "There are no folders here.",
	selected: "Selected:",
	openFolder: "Open folder",
	useFolder: "Use this folder",
	browserNote:
		"A folder that is not a git project can’t be used yet. For a new project, go back and choose “No, start a new one”: Farik makes the folder and sets up git for you.",
	opening: "Opening your project…",
	takeOnError: "Farik could not open that project.",
	scanTitle: "Here is what Farik found in your project",
	scanLead:
		"Farik read the folder without changing anything. Your team starts from this, so tell us if something is wrong.",
	scanFound: "What Farik found",
	scanWhat: "What it is",
	scanTested: "How it is tested",
	scanChecked: "How it is checked",
	scanLast: "Last change",
	scanPrivate: "Kept private",
	scanWorkspace: "a workspace of {count} packages",
	scanUnknown: "Farik could not tell",
	scanTestsIn: "Tested with {location}",
	scanNoTests: "No tests found",
	scanNoChecks: "No checks found",
	scanNoCommits: "No changes yet",
	scanPrivateNote: "No agent will ever open them.",
	scanNothingPrivate: "Nothing private found",
	scanChecksNote:
		"The checks found become your first checks. Farik runs them itself on every piece of work before it reaches you.",
	scanWrong: "Something is wrong",
	scanWrongField: "What is wrong?",
	scanWrongHint:
		"Your team reads this before it starts, for example: it is a shop, not a game.",
	scanWrongSave: "Tell the team",
	scanWrongSaved: "Saved. Your team reads it before it starts.",
	scanRight: "That's right",
	teamTitle: "Who should be on your team?",
	teamLead:
		"We suggest six, one for each job. You can rename them now or later. To add a second developer, choose “Add someone”.",
	teamMembers: "Your team",
	teamInclude: "Include the {role}",
	jobProductManager:
		"Turns what you ask for into a plan, and asks you when something is unclear.",
	jobScrumMaster: "Hands out the work and keeps the team unblocked.",
	jobArchitect:
		"Keeps the project well built, and reviews the work before you see it.",
	jobDeveloper: "Builds and tests what the plan asks for.",
	jobMarketing: "Writes posts, pages and a plan for getting the word out.",
	jobDesigner:
		"Looks at your app the way a customer does, plans changes to its screens, and makes them once {pm} agrees. Checks every screen {developer} builds.",
	teamName: "Name for the {role}",
	teamAdd: "Add someone",
	teamContinueSix: "Continue with these six",
	teamContinue: "Continue with this team",
	roleProductManager: "Product Manager",
	roleScrumMaster: "Scrum Master",
	roleArchitect: "Architect",
	roleDeveloper: "Developer",
	roleMarketing: "Marketing Specialist",
	roleDesigner: "UI/UX Designer",
	mayTitle: "What may your team do on its own?",
	mayLead:
		"Two things can cause real harm, so Farik asks you about them directly. Nothing runs until you answer both.",
	mayCommands: "May the team run commands on this computer?",
	mayCommandsNote:
		"Running the tests and trying the app needs this. Commands run in a sealed box, away from your other files.",
	mayCommandsYes: "Yes, the Developer and Architect may",
	mayCommandsYesNote:
		"Recommended. Without it nobody can check that the code works.",
	mayCommandsNo: "No, nobody may",
	mayCommandsNoNote: "The team can plan and write, but cannot test anything.",
	mayStillChecks:
		"Farik still runs every check itself; the agents cannot run commands.",
	mayPush: "May the Developer send its work to your online repository?",
	mayPushNoteOne:
		"Only {name}, the Developer, ever sends code, and only to its own fix or feature branch. Farik sends the other agents’ documents itself. Nothing reaches your main branch without you.",
	mayPushNoteMany:
		"Only the Developers ever send code, and only to their own fix or feature branches. Farik sends the other agents’ documents itself. Nothing reaches your main branch without you.",
	mayPushYes: "Yes, on its own branches",
	mayPushYesNote: "Useful if you review work on GitHub.",
	mayPushNo: "No, keep everything on this computer",
	mayPushNoNote: "The safer choice. You can change it later in Team.",
	mayAlready: "What each agent may do already",
	mayAnswerBoth: "Answer both questions to continue.",
	spendTitle: "Do you want a daily spending limit?",
	spendLead:
		"Each agent uses an AI model, and each piece of work costs a little. You can set a limit, or leave it open and watch costs on the Costs page.",
	spendChoice: "Daily spending limit",
	spendNone: "No limit",
	spendNoneNote:
		"The team keeps working until the work is done. Best if you pay a flat monthly subscription for your AI model.",
	spendDaily: "Stop the team after a set amount each day",
	spendDailyNote:
		"When the team reaches the limit, everyone pauses and you get a message. They carry on the next day, or sooner if you raise the limit.",
	spendAmount: "Limit per day, in US dollars",
	spendAmountWrong: "Enter an amount above zero, such as 10.",
	spendFixed:
		"Some limits are always on, whatever you choose. No agent works on one thing for more than 30 minutes at a time, and a piece of work sent back three times comes to you.",
	firstDay:
		"A first full day for the suggested team of six costs about twenty-five dollars (an estimate) on your own key at today’s prices. A smaller team costs less.",
	finishTitle: "When you accept a piece of work, what happens to it?",
	finishLead:
		"Accepted work has to be added to your project. Choose how much you want to do by hand.",
	finishChoice: "Accepted work",
	finishAuto: "Farik adds it for me",
	finishAutoNote:
		"Recommended. Farik adds the work to your project as soon as you accept it, and sends it to your online repository if you have one.",
	finishPullRequest: "Open a pull request on GitHub for each piece",
	finishPullRequestNote:
		"You, or someone you trust, merges each one on GitHub. Needs the GitHub app on this computer.",
	finishManual: "I will add each one myself",
	finishManualNote:
		"Farik waits. Each accepted piece shows an “Add to project” button until you press it.",
	finishSafe:
		"Rules for the whole team, the checks every piece of work must pass, and how plans are judged are already set to safe choices.",
	startTeam: "Start the team",
	advancedHide: "Hide advanced settings",
	advancedLead:
		"These are already set to safe choices. Change them only if you want to. You can come back to them any time in Settings.",
	rulesTitle: "Team rules",
	rulesLead: "Rules every agent follows, and that no agent can change.",
	editAsText: "Edit as text",
	rulesText: "Team rules, as text",
	rulesTextUse: "Use this text",
	rulesTextWrong:
		"This is not a set of team rules. Check the text, then try again.",
	rulePrivate: "Keep private files private",
	rulePrivateNote:
		"No agent may open passwords and keys: .env files, and key files.",
	ruleTests: "Every code change comes with new tests",
	ruleTestsNote:
		"A plan for code is not ready until it asks for tests of the change.",
	ruleDeveloper: "Only the Developer changes code",
	ruleDeveloperNote: "Everyone else may only change documents and plans.",
	ruleMaxCost: "Most one piece of work may cost",
	ruleMaxCostHint: "In US dollars. Leave it empty for no limit.",
	alwaysOn: "Always on",
	checksTitle: "Checks for every piece of work",
	checksLead: "Farik runs these itself before work reaches you.",
	checkFound: "Found in your project. Runs: {command}",
	checkYours: "Added by you.",
	checkReviewed: "Someone on the team reviewed it",
	checkReviewedNote: "Another agent reads the work before you see it.",
	checkNew: "A new check",
	checkNewHint:
		"Say what must be true of finished work, in at least 10 characters. Another agent checks it.",
	checkAdd: "Add a check",
	planTitle: "Checking plans",
	planLead: "Before anyone starts, one agent checks that the plan makes sense.",
	planRequired: "Check every plan before work starts",
	planQuestions: "What the checker asks about each plan",
	planBudget: "Can this be done within its budget?",
	planBudgetNote: "So work does not stop halfway because the money ran out.",
	planNotice: "Would the checks notice if it went wrong?",
	planNoticeNote: "So a broken result cannot pass as finished.",
	planSmall: "Is it small enough to finish in one go?",
	planSmallNote: "Big plans get split into smaller pieces first.",
	planJudge: "Who checks",
	planJudgeAuto: "Farik chooses: {who}",
	planJudgeNamed: "{name}, the {role}",
	planJudgeNone: "The {role}, once the team has one",
	team: "Team",
	teamPageLead:
		"{count} agents work on {name}. A team needs a Product Manager and a Developer; everyone else is up to you. You can have up to seven.",
	agentEditLink: "Edit {name}",
	agentPause: "Pause {name}",
	agentResume: "Resume {name}",
	agentActive: "On the team",
	agentPaused: "Paused",
	agentModel: "Model",
	agentModelRole: "The role’s model",
	teamChangesTitle: "Pause, retire or replace",
	teamChangesBody:
		"Pausing stops an agent from taking new work; it finishes nothing halfway. Retiring removes it from the team but keeps what it learned in your project, so whoever replaces it can read it. Changes start with the agent’s next piece of work, never in the middle of one.",
	teamCostTitle: "What a team like this costs",
	teamCostNote: "It is a guide, not a limit.",
	teamCostDesigner:
		"{designer} uses the same model as {developer}, so {designer} adds to what a day costs. Before {designer} changes a screen, {designer} looks at it and writes a plan, and that costs a little too.",
	teamCostLimitBefore: "Set a limit in ",
	teamCostLimitAfter: ".",
	agentBack: "Back to your team",
	agentTitle: "{name}, your {role}",
	agentMissing: "There is no agent called {id} on your team.",
	agentName: "Name",
	agentTalks: "How {name} talks",
	agentTalksHint:
		"One line. It shapes {name}’s messages in the channel, not the quality of the work.",
	agentEffort: "How carefully {name} works",
	effortLow: "Quick",
	effortLowNote: "Cheaper, for simple jobs",
	effortMedium: "Balanced",
	effortMediumNote: "Good for most work",
	effortHigh: "Careful",
	effortHighNote: "Thinks longest; costs most",
	agentMay: "What {name} may do",
	agentMayAdvanced: "Turn on Advanced to see each permission.",
	tierRead: "Read the project",
	tierReadNote: "Every agent can.",
	tierWrite: "Change files in its task",
	tierWriteNote: "Only the files the plan allows.",
	tierExecute: "Run commands",
	tierExecuteNote: "Inside a safe box on your computer.",
	tierGitLocal: "Save its work on its own branch",
	tierGitLocalNote: "Never on your main branch.",
	tierNetwork: "Use the internet",
	tierNetworkNote: "Looks things up and reads web pages.",
	tierGitRemote: "Push to GitHub and open pull requests",
	tierGitRemoteNote: "Nobody has this until you give it.",
	tierExternal: "Do things outside your computer",
	tierExternalNote: "Sending mail, posting, deploying. You approve each one.",
	agentDefaults: "Put back the role’s defaults",
	agentEffects: "What this changes",
	agentPlace: "{name}’s place on the team",
	agentPauseNote:
		"{name} finishes nothing halfway and takes no new work until you resume.",
	agentReplace: "Replace {name}",
	agentReplaceNote: "A new {role} joins and starts from what {name} learned.",
	agentRetire: "Retire {name}",
	agentRetireNote:
		"{name} leaves the team. What {name} learned stays in your project for whoever comes next.",
	agentSave: "Save changes",
	agentCancel: "Cancel",
	agentNextWork: "Changes start with {name}’s next piece of work.",
	accountRow: "Your AI account",
	accountConnected: "Claude, with {kind}.",
	accountApiKey: "an API key",
	accountSubscription: "your Claude subscription",
	accountKeychain: "Kept in your computer’s keychain.",
	accountFile: "Kept in a private file on this computer.",
	accountEnvironment: "Read from this computer’s environment.",
	accountNone: "No AI account is connected.",
	accountKeyRefused:
		"The key did not work, so your team is paused. Connect your AI account again with a new key.",
	accountConnectAgain: "Connect again",
	accountKeyRefusedEnvironment:
		"The key in {variable} did not work, so your team is paused. Change it where Farik runs, start Farik again, then press Resume.",
	accountDisconnect: "Disconnect this account",
	accountGone:
		"Disconnected. The team is paused; start Farik again to connect another account.",
	accountKept:
		"Farik reads this key from the {variable} variable on this computer, so it cannot remove it. Remove it there, then start Farik again.",
	statusPlanning: "Planning",
	statusBacklog: "Backlog",
	statusToDo: "To do",
	statusInProgress: "In progress",
	statusReworked: "Being reworked",
	statusReview: "Review",
	statusDone: "Done",
	statusStuck: "Stuck",
	statusWaiting: "Waiting on you",
	statusHelp: "Needs your help",
	statusCancelled: "Cancelled",
	teamBand: "Your team",
	sprintLine: "Sprint {n} is running: {done} of {total} tasks done",
	requestLabel: "What should the team do next?",
	requestHint:
		"{name} reads every request and asks you if anything is unclear.",
	requestSend: "Send to the team",
	requestTooShort:
		"Say a little more about what you want the team to do: at least 20 characters.",
	waitingTitle: "Waiting on you ({count})",
	waitingList: "Waiting on you",
	waitingNone: "Nothing waits on you.",
	waitingApproval: "Approve the plan for {title}",
	waitingAcceptance: "Accept {title}",
	waitingQuestion: "{agent} has a question",
	waitingHelp: "{agent} needs your help",
	waitingIntegration: "Add {title} to your project",
	waitingReview: "Review",
	waitingAnswer: "Answer",
	waitingHelpButton: "Help",
	waitingAdd: "Add",
	waitingKeyRefused: "Your AI account’s key did not work",
	waitingKeyRefusedLine:
		"The team is paused until you connect your AI account again.",
	waitingKeyConnect: "Connect again",
	checksPassed: "All {count} of Farik’s checks passed.",
	movedTitle: "What moved since yesterday",
	yesterday: "Yesterday",
	yesterdayShort: "Yday",
	movedNone: "Nothing moved since yesterday.",
	backToToday: "Back to Today",
	requestTitle: "Your request is with the team",
	requestSent: "{id}, sent at {time} UTC.",
	youAsked: "You asked",
	sizing: "{name} is sizing your request…",
	sizedAs: "{name} sized it as {size}",
	youSizedAs: "You sized it as {size}",
	sizeLarge: "a big request",
	sizeSmall: "a small request",
	decided: "{name}, your {role}, decided",
	sizeLargeCard: "A big request",
	sizeLargeBody:
		"{pm} writes a plan with parts, asks you what is needed, and waits for your approval before anyone starts building.",
	sizeSmallCard: "A small request",
	sizeSmallBody:
		"One task, planned and built straight away. Choose this if you only want a first, simple version.",
	sizeChosen: "This is what {name} chose.",
	sizeChosenByYou: "This is what you chose.",
	resizeToSmall: "Change this to a small request",
	resizeToLarge: "Change this to a big request",
	resizeReason: "Changed by you",
	nextTitle: "What happens next",
	nextLarge1: "{pm} asks you a few questions. You will see them on Today.",
	nextLarge2: "{pm} writes the plan and Farik checks it is complete.",
	nextLarge3: "You approve the plan, or ask for changes.",
	nextLarge4: "{breaker} splits it into tasks and the team starts.",
	nextSmall1:
		"{pm} asks you anything that is unclear. You will see it on Today.",
	nextSmall2: "{pm} writes the plan and Farik checks it is complete.",
	nextSmall3: "The team builds it, and a teammate reviews the work.",
	nextSmall4: "You accept the work, or send it back with a note.",
	aboutRequest: "About this request",
	aboutSent: "Sent",
	aboutSizedBy: "Sized by",
	aboutPlannedBy: "Planned by",
	aboutPlanId: "Plan id",
	aboutStatus: "Status",
	nameRole: "{name}, {role}",
	you: "You",
	notYet: "Not yet",
	questionsTitle: "{agent}’s questions",
	questionsLead:
		"Plan {id}. {agent} asks before writing the plan, so the plan matches what you want.",
	questionsNone: "There are no questions for {id}.",
	youAnswered: "You answered:",
	answered: "Answered",
	laterQuestion: "{agent} shows this once you answer question {n}.",
	suggests: "{agent} suggests",
	ownWordsMany: "Or say it in your own words",
	wordsWin: "Your own words are sent instead of the choice.",
	ownWordsOne: "Or answer in your own words",
	sendAnswer: "Send answer",
	letDecide: "Let {agent} decide",
	decideText: "Decide as you think best, and say what you chose.",
	oneQuestionTitle: "{agent} has a question",
	oneQuestionLead: "About {id}. {agent} stopped until you answer.",
	asks: "{agent}, your {role}, asks",
	aboutQuestions: "About questions",
	aboutQuestionsBody:
		"A question is not a problem. {agent} just needs your answer to carry on.",
	aboutQuestionsNext: "Your answer goes straight into {agent}’s next session.",
	approveTitle: "Approve the plan for {title}",
	approveLead: "Plan {id}.",
	approveLeadTask:
		"Plan {id}. It waits for your approval before anyone builds it.",
	approveLeadEpic:
		"Plan {id}. Every plan with parts waits for your approval before anyone builds it.",
	planSigned: "{name}, your Product Manager, wrote this for you",
	planParts: "The plan in {n} parts",
	planPartsHint: "The line under each part is how Farik will know it is done.",
	planDoneWhen: "Done when {text}",
	planWholeDoneWhen: "The whole plan is done when",
	planOut: "Not in this plan",
	planChecked: "What Farik checked",
	planCheckedAll:
		"The plan is complete enough for the team to start. Farik checks this itself.",
	checkPassed: "Passed",
	checkNotYet: "Not yet",
	planWritten: "See the plan as written",
	planAbout: "About this plan",
	approveQuestions: "Questions",
	planAnswered: "{n} answered",
	planRisk: "Risk",
	riskLow: "Low",
	riskMedium: "Medium",
	riskHigh: "High",
	planEstimate: "Estimate",
	planBuilders: "Builders",
	planEdit: "Edit the plan yourself",
	planApprove: "Approve the plan",
	planAskChanges: "Ask for changes",
	planApproveNote:
		"Approving lets {breaker} split the plan into tasks for the team.",
	planAskTitle: "Ask {pm} for changes",
	planAskNote: "What should change?",
	planAskSend: "Send it back",
	editTitle: "Edit the plan for {title}",
	editBack: "Back to the plan",
	editAdvanced: "Advanced view",
	lockOpen: "{pm} can still change this plan",
	lockOpenHint: "Lock it so that only you change it.",
	lockButton: "Lock the plan",
	lockClosed: "You have locked this plan",
	lockClosedHint: "{pm} cannot change it until you unlock it.",
	unlockButton: "Unlock",
	holdTitle: "The team is working to this plan",
	holdHint:
		"To change it, hold the work first. The task then waits for you until you save.",
	holdButton: "Hold the work",
	holdReason: "Held by you to change the plan",
	fieldIntent: "Why you want it",
	fieldIntentHint: "Says why, from the customer’s side.",
	fieldSummary: "The summary you read first",
	fieldParts: "The parts of the plan",
	fieldPart: "Part {n}",
	addPart: "Add a part",
	removePart: "Remove part {n}",
	fieldCriteria: "How we will know it is done",
	fieldCriteriaHint: "Each check says how it is checked.",
	fieldCriterion: "Check {n}",
	criterionWho: "Who checks it",
	criterionReview: "Someone on the team reviews it",
	criterionHuman: "You decide",
	criterionCommand: "Farik runs a command",
	criterionCommandField: "The command",
	criterionCommandLocked:
		"Farik runs a command. Turn on Advanced view to change it.",
	addCriterion: "Add a check",
	removeCriterion: "Remove check {n}",
	fieldOut: "What is left out",
	fieldOutHint:
		"One per line. Name at least one thing this plan does not do. It keeps the work from growing.",
	fieldBudget: "Spending limit in dollars",
	fieldRisk: "How risky it is",
	fieldPaths: "Files the team may change",
	fieldPathsHint: "One per line. Inside the paths your team rules allow.",
	verdictTitle: "Ready to approve?",
	verdictCount: "{n} of {total} checks pass.",
	verdictOne: "The one left: {plain}",
	verdictMany: "Still to do:",
	verdictNote:
		"Farik checks the plan as you type. The results come from your project, not from this page.",
	editSave: "Save",
	savedBack:
		"Saved. {pm} checks the plan again, then it comes back to you to approve.",
	saved: "Saved.",
	editClash:
		"{pm} changed this plan while you were editing. Your changes are kept.",
	editTakeNew: "Take the new version",
	gateTitle: "Accept {title}",
	gateLead: "{id}. The work waits for you to accept it.",
	gateWrote: "{name}, your {role}, wrote this for you",
	gateReviewed: "{name}, your {role}, reviewed it",
	gateReviewedAfter:
		"{name}, your {role}, reviewed the code after {designer} passed the screens",
	gateCheckedHint:
		"Farik ran these checks itself. It did not take the team’s word for them.",
	gateSeeChanges: "See the code changes",
	gateHideChanges: "Hide the code changes",
	gateSize: "{n} files, +{added} −{removed}",
	gateSizeOne: "1 file, +{added} −{removed}",
	gateChanges: "The code changes",
	gateAbout: "About this task",
	gatePlanApproved: "Plan approved",
	gateTries: "Tries",
	triesOf: "{try} of {of}",
	gateCost: "Cost",
	gateHistory: "See the whole history",
	gateScreensChecked: "Screens checked",
	gateScreensCheckedBy: "{day}, by {name}",
	gateCodeReviewed: "Code reviewed",
	gateWhoLooked: "Who looked at it, in order",
	gateLookedFarik: "Farik ran its checks",
	gateLookedScreens: "{name} checked the screens",
	gateLookedScreensBack: "{name} sent the screens back",
	gateLookedCode: "{name} reviewed the code",
	gateLookedCodeBack: "{name} sent the code back",
	gateLookedYou: "Now you decide",
	gateWhatChecked: "What you checked",
	gateAccept: "Accept the work",
	notWaiting: "This does not wait on you now. Where it is: {status}.",
	gateSendBack: "Send back with a note",
	gateAdd: "Add to project",
	sendBackTitle: "Send the work back to {name}",
	sendBackWhat: "What is not right? Choose any that apply.",
	sendBackElse: "Something else",
	sendBackNote: "Your note to {name}",
	sendBackTry:
		"This is try {try} of {of}. After the last, Farik stops and asks you what to do.",
	sendBackCancel: "Cancel",
	sendBackSend: "Send back to {name}",
	helpTitle: "{name} needs your help with “{title}”",
	helpExplains: "{name}, your {role}, explains what happened",
	helpFarikExplains: "Farik explains what happened",
	helpReadPlan: "Read the plan",
	helpNothing: "There is nothing to choose here yet.",
	helpTried: "What {name} tried",
	helpNow: "What should happen now?",
	helpNote: "A note for {name} (optional)",
	helpWaiting: "Waiting since",
	helpSpent: "Spent",
	helpSpentOf: "{spent} of {max}",
	helpReviewer: "Reviewer",
	refuseTooMany:
		"A team has seven people at most. Retire someone before adding another.",
	refuseNeedsProductManager:
		"Your team needs a Product Manager to write its plans. Include one.",
	refuseNeedsDeveloper:
		"Your team needs a Developer to do the work. Include one.",
	refuseRepeatedId: "Two people on the team have the same name. Rename one.",
	refuseWorked:
		"Someone you took off the team has already done work. Retire them from their card instead.",
	refuseName: "Give everyone a name.",
	refuseKeepsRead:
		"Every agent reads the project. Pause the agent instead of taking reading away.",
	refuseStatusFromCard: "Pause, retire or resume someone from their card.",
	refuseJudge:
		"Nobody on the team is an active {role}. Let Farik choose who checks, or add a {role}.",
	refuseNoQuestions:
		"Checking plans needs at least one question. Tick one, or stop checking plans.",
	refuseQuestionLength: "A question is 10 to 200 characters long.",
	refuseLastOfRole: "{name} is your only {role}, so add another {role} first.",
	refuseLastJudge:
		"{name} checks your plans. Let Farik choose who checks, or add another {role}, first.",
	refuseOther:
		"Farik could not make this change. Check what you changed, then try again.",
	refuseAlreadyPaused: "The team is already paused.",
	refuseNotPaused: "The team is already working.",
	refuseAlreadyAnswered: "This question already has an answer.",
	refuseAlreadyAccepted: "You have already accepted this work.",
	refuseNotWaiting:
		"This is not waiting for you any more. Reload the page to see where it is now.",
	refuseReviewFirst:
		"The reviewer has not finished yet. Send it back once their review is in.",
	refuseChecksNotRun:
		"Farik has not finished checking this work yet. Try again once the checks have run.",
	refuseChecksFailed:
		"Some checks failed once the parts were put together, so this cannot be accepted yet. Send it back with what is missing.",
	refuseUsePlan:
		"This plan is waiting for your approval. Approve it from its plan page.",
	refuseUseHelp:
		"This task is waiting for your help. Answer it from its help page.",
	refuseExtraTries:
		"More tries come only with sending the work back to be done, for a task that used up its tries.",
	refuseSameStatus: "That is already so, so nothing changed.",
	refuseAgentRetired:
		"This teammate has left the team, so this chat can be read but not added to.",
	refuseSprintOpen: "A sprint is already open. End it before starting another.",
	refuseNoSprintOpen: "No sprint is open right now.",
	refuseTriage:
		"Farik could not size this request. Reload the page to see where it is now.",
	refuseLock:
		"Farik could not take or give back this plan. Reload the page to see where it is now.",
	refuseCommand: "Farik could not do that. Reload the page, then try again.",
	planHoldFirst:
		"The team is working to this plan. Hold the work first, then change it.",
	requestSentAs: "This was already sent, as {id}.",
	setupNoFolder: "That folder is not there any more. Choose another.",
	setupOutsideHome: "Choose a folder inside your home folder.",
	setupUnreadable: "Farik cannot open that folder. Choose another.",
	setupNotGit:
		"That folder is not a git project. Choose another, or start a new project.",
	setupInsideGit:
		"That folder is inside a git project. Choose the project’s top folder instead.",
	setupBusy: "Farik is already running this project.",
	setupNoAccount: "Connect your AI account first.",
	setupName:
		"A project’s name is lowercase letters, digits and dashes, up to 64 characters.",
	setupDescribeMore:
		"Say a little more about the project: at least 20 characters.",
	setupDescribeLess:
		"That description is too long. Keep it to 2,000 characters.",
	setupNameTaken:
		"A folder with that name is already there. Choose another name.",
	setupNoGit: "Git is not installed on this computer.",
	setupNotSubscription:
		"That is not a subscription key. A subscription key starts with sk-ant-oat.",
	setupNotApiKey: "That is not an API key. An API key starts with sk-ant-api.",
	setupNoKeep:
		"This computer has no keychain and no folder to keep the key in.",
	setupKeyFromEnvironment:
		"Your AI account’s key is set where Farik runs. Change it there, then start Farik again.",
	setupNoDocker: "Docker is not installed on this computer.",
	setupBuildFailed:
		"Farik could not prepare the sandbox. Check that Docker is running, then try again.",
	setupPullFailed:
		"Farik could not fetch the browser. Check that Docker is running and you are online, then try again.",
	setupRefused:
		"Farik could not do that. Check what you entered, then try again.",
	pageNotFound: "This is not here any more. It may have been removed.",
	pageFailed: "Farik could not open this page. Reload it to try again.",
	teamAddRole: "Their role",
	teamFull:
		"Your team has seven people, the most it can have. Retire someone to make room.",
	mayRead: "reads the project",
	mayWrite: "changes the files of its task",
	mayExecute: "runs commands in a sealed box",
	mayGitLocal: "saves its work on its own branch",
	mayNetwork: "looks things up on the web",
	mayGitRemote: "sends its work to its own branches online",
	mayExternal: "acts outside your computer, with your approval",
	putBack: "Put back the default",
	rulesArea: "Your team’s rules",
	rulesNextSession:
		"The answers you gave in setup, to change whenever you like. Each change starts with each agent’s next session, never in the middle of one.",
	rulesMay: "What agents may do",
	rulesSpend: "Daily spending limit",
	rulesSpendTitle: "What the team may spend",
	rulesFinish: "How finished work is added",
	accountConfirm:
		"Disconnecting pauses your team until you start Farik again and connect an account.",
	accountDisconnectYes: "Disconnect and pause the team",
	board: "Board",
	costs: "Costs",
	sprintNone:
		"No sprint is running. The team works through the board in order.",
	sprintStart: "Start a sprint",
	sprintEndEarly: "End the sprint early",
	boardFilters: "Filters",
	filterEveryone: "Everyone",
	filterWaiting: "Only what is waiting on me",
	filterMore: "More filters",
	filterSprint: "Sprint",
	filterSprintAll: "All",
	filterSprintThis: "This sprint",
	filterSprintNone: "No sprint",
	filterRisk: "Risk",
	filterRiskAny: "Any",
	filterCancelled: "Show cancelled",
	laneTabs: "Lanes",
	laneEmpty: "Nothing here right now.",
	markAccepted: "Accepted",
	markWriting: "Writing",
	markBuilding: "Building",
	markReviewing: "Reviewing",
	markPlanning: "Planning",
	epicParts: "{parts} parts, {done} done",
	epicPartsOne: "1 part, {done} done",
	sprintStartTitle: "Start sprint {n}",
	sprintStartWhat:
		"A sprint is a batch of work the team finishes before it stops to look back. It ends by itself when every task in it is done.",
	sprintStartPlanner:
		"{name} will plan it: {name} picks from the {count} ready tasks on the board, posts the plan in the channel, and then runs a short standup each day and a review and a look back at the end.",
	sprintLimit: "Spending limit for this sprint",
	sprintNoLimit: "No limit",
	sprintLimitAfter: "Stop handing out new work after",
	sprintLimitDollars: "Dollars",
	sprintLimitHint:
		"When the limit is reached, work already started may finish. You can leave it empty and watch spending on the Costs page.",
	sprintNotNow: "Not now",
	sprintEndTitle: "End sprint {n} early?",
	sprintEnd: "End sprint {n}",
	sprintEndLeaves:
		"{count} tasks are not finished. They leave the sprint and go back on the board exactly as they are. Nothing is lost, and work in progress keeps going. {name} will still run the review and the look back.",
	sprintEndLeavesOne:
		"1 task is not finished. It leaves the sprint and goes back on the board exactly as it is. Nothing is lost, and work in progress keeps going. {name} will still run the review and the look back.",
	sprintKeep: "Keep it running",
	sprintNoneBacklog:
		"No sprint is running. Ready work waits in the Backlog until you start one.",
	sprintMoreOne: "1 more waits in the Backlog for the next sprint.",
	sprintMore: "{count} more wait in the Backlog for the next sprint.",
	laneBacklogNote: "Ready work waits here until you start a sprint.",
	laneBacklogLate: "Waits here for the next sprint.",
	backlogReady: "Ready",
	backlogNextSprint: "Ready. Waits for the next sprint",
	backlogEpicReady: "Ready, broken into {count} tasks",
	backlogEpicReadyOne: "Ready, broken into 1 task",
	sprintStartBacklog: "Waiting in the Backlog",
	sprintStartEpic: "Epic, {count} tasks",
	sprintStartEpicOne: "Epic, 1 task",
	sprintStartTask: "Task",
	sprintStartPlansBacklog:
		"{name} plans it: {name} picks from this work, posts the plan in Chats, under Team, and then runs a short standup each day and a review and a look back at the end. Work that becomes ready later waits for the next sprint.",
	sprintEndBacklog:
		"{count} tasks are not finished. They leave the sprint and wait in the Backlog for the next one. A session already running finishes. {name} will still run the review and the look back.",
	sprintEndBacklogOne:
		"1 task is not finished. It leaves the sprint and waits in the Backlog for the next one. A session already running finishes. {name} will still run the review and the look back.",
	todayBacklog: "{count} pieces of work are ready and wait in the Backlog.",
	todayBacklogOne: "1 piece of work is ready and waits in the Backlog.",
	todayBacklogStart: "Start a sprint",
	todayBacklogBegin: "to begin them.",
	todayBacklogBeginOne: "to begin it.",
	rulesPlanning: "Planning work",
	planInSprints: "Plan work in sprints",
	planInSprintsNote:
		"The team gets work ready at any time: it asks its questions, writes the plans and has them checked, and breaks big requests into tasks. Nobody starts building until you start a sprint. Work that becomes ready during a sprint waits in the Backlog for the next one.",
	finishSprints: "Your team works in sprints",
	finishSprintsNote:
		"The team gets your requests ready straight away, and starts building when you start a sprint from the Board. Until then, ready work waits in the Backlog.",
	finishSprintsChange:
		"Change this under advanced settings, or later in Settings.",
	taskBack: "Back to the board",
	taskInSprint: "{id} in sprint {n}.",
	taskDoing: "{name} is doing it",
	taskReviews: "{name} reviews it",
	taskTry: "Try {try} of {of}.",
	taskTabs: "About this task",
	tabSummary: "Summary and checks",
	tabHistory: "History",
	tabPlan: "The plan",
	tabChanges: "Code changes",
	tabNotes: "Notes",
	taskFor: "What this task is for",
	taskChecks: "What Farik checks",
	checkFailed: "Failed last time",
	checkNotRun: "Not run yet",
	taskHistoryHint:
		"Everything that happened to this task, newest first. The grey names are what Farik records in its log.",
	toldCreated: "{who} asked for it.",
	toldMoved: "{who} moved {task} to {status}.",
	toldIt: "it",
	toldApproved: "{who} approved the plan.",
	toldAccepted: "{who} accepted the work.",
	toldSentBack: "{who} sent {task} back.",
	toldNote: "{who} left a note.",
	toldReview: "{who} reviewed it.",
	toldCheck: "Farik ran a check.",
	toldStarted: "{who} started working on it.",
	toldEnded: "{who} finished a session.",
	toldCost: "{who} spent {usd}.",
	toldEscalated: "{who} asked for your help.",
	toldResolved: "{who} answered the call for help.",
	toldIntegrated: "It was added to the project.",
	toldPlan: "The plan was written or checked.",
	toldOther: "Farik recorded this in its log.",
	toldLocked: "{who} locked the plan.",
	toldUnlocked: "{who} unlocked the plan.",
	toldAsked: "{who} asked you a question.",
	toldAnswered: "{who} answered a question.",
	toldTriaged: "{who} sized up the request.",
	toldLimit: "A spending limit was reached.",
	toldRefused: "Farik did not allow a move to {status}.",
	toldAged: "The call for help has been waiting a while.",
	toldPullRequest: "Farik opened a pull request for it.",
	toldPlanned: "{who} planned it into a sprint.",
	toldDrift: "Farik found its files out of step with its log.",
	toldSaid: "{who} said something about it in the channel.",
	toldDenied: "Farik stopped a step {who} tried.",
	toldDesignProposed: "{who} wrote a plan.",
	toldDesignApproved: "{who} approved {designer}’s plan.",
	toldDesignReturned: "{who} sent {designer}’s plan back.",
	designLead:
		"{designer} looked at your app and wrote this. {designer} changes nothing until {pm} approves it.",
	designWaiting: "Waiting for {pm} to approve the plan",
	designWaitingNote:
		"{pm} checks that the plan does what the task asks, and nothing more. You do not need to do anything.",
	designBeingBuilt: "Being built",
	designBeingBuiltNote:
		"{designer} is changing the page now, as the plan says.",
	designSentBack: "Plan sent back",
	designSentBackNote:
		"{designer} is looking at the page again and will write a new plan.",
	designApproved: "{pm} approved the plan {day} at {time}",
	designReturned: "{pm} sent the plan back {day} at {time}",
	designReturns:
		"Plans sent back: {n} of {of}. If a {nth} is sent back, Farik stops the task and asks you.",
	designReturnsMany:
		"Plans sent back: {n} of {of}. If {of} are sent back, Farik stops the task and asks you.",
	designWrote: "{designer} wrote this plan {day} at {time}",
	designToday: "today",
	designOnDay: "on {day}",
	designPlanCount: "{Nth} plan.",
	designPlanCountMany: "Plan {n}.",
	taskPlanApproved: "Approved on {day}.",
	taskPlanNotApproved: "Not approved yet.",
	taskPlanLocked: "It is locked, so nobody can change it while the work runs.",
	taskPlanOpen: "It is not locked yet, so it can still change.",
	taskScope: "What is in scope",
	taskOutOfScope: "Out of scope",
	taskRisk: "Risk",
	taskLimit: "Spending limit",
	taskLimitFor: "{usd} for this task",
	taskChangesLine: "{size}, on the branch {branch}.",
	taskNoNotes: "No notes yet.",
	taskCost: "Cost so far",
	taskCostTotal: "Total, of a {limit} limit",
	taskAddTitle: "Adding it to your project",
	taskAddHint:
		"Once the task is accepted, Farik adds its changes to your main branch, one task at a time.",
	taskAdd: "Add to the project",
	taskAddNotYet: "Not yet: the task has not been accepted.",
	taskAddOnItsOwn: "Accepted. Farik adds it to your project on its own.",
	taskAddByPullRequest:
		"Accepted. Farik opens a pull request for it, for you to merge.",
	taskAddByHand: "Accepted. It waits for you to add it.",
	riskLowWhy: "Low. The team may accept it without you.",
	riskMediumWhy: "Medium. The team may still accept it without you.",
	riskHighWhy: "High. You approve its plan, and you accept the work yourself.",
	taskAdded: "Added on {day}.",
	taskStop: "Stop work on this task",
	taskCancel: "Cancel this task",
	taskCancelTitle: "Cancel {title}?",
	taskCancelWhy: "Why cancel it?",
	taskCancelKeep: "Keep it",
	sprintTitle: "Sprint {n}",
	sprintBack: "Back to the board",
	sprintStartedBy: "Started {day} by {who}.",
	sprintPlannedBy: "Planned by {name}.",
	sprintEndedOn: "Ended {day}.",
	sprintYou: "you",
	sprintTasks: "In this sprint",
	sprintTasksDone:
		"{done} of {total} done. The sprint ends by itself when the last one is accepted or cancelled.",
	sprintMeetings: "Team meetings",
	sprintMeetingsLead:
		"{name} runs these in the channel. Each one is a short post you can read in a minute.",
	sprintNoMeetings: "No meetings yet.",
	meetingPlanning: "Planning",
	meetingStandup: "Standup",
	meetingReview: "Review",
	meetingRetro: "Looking back",
	meetingPosts: "{posts} posts on {day}",
	meetingPostsOne: "1 post on {day}",
	sprintSpending: "Spending",
	sprintSpentOf: "{spent} so far, of the {budget} you set for this sprint.",
	sprintSpentNoLimit: "{spent} so far, with no limit set for this sprint.",
	sprintSeeCosts: "See costs by agent",
	costsToday: "Today the team has spent {spent}, with no daily limit set.",
	costsTodayOf: "Today the team has spent {spent}, of {limit} a day.",
	costsSprint: "Sprint {n} has spent {spent} of its {budget} limit.",
	costsSprintNoLimit: "Sprint {n} has spent {spent}, with no limit.",
	costsSprintEnded:
		"Sprint {n} has ended. It spent {spent} of its {budget} limit.",
	costsSprintEndedNoLimit:
		"Sprint {n} has ended. It spent {spent}, with no limit.",
	costsSprintEndedColumn: "Sprint {n}",
	costsSprintWhy:
		"Planning meetings, and work done before a task joined the sprint, count toward the day, not the sprint.",
	costsSetLimit: "Set a daily limit",
	limitSave: "Save the limit",
	costsByAgent: "By agent",
	costsAgent: "Agent",
	costsTodayColumn: "Today",
	costsSprintColumn: "This sprint",
	costsNow: "Right now",
	costsResting:
		"Resting is not a problem. An agent whose AI account reached its usage limit stops, writes down where it was, and picks up again at the time shown. The rest of the team keeps working.",
	costsConversations: "Conversations today:",
	costsConversationsWhy:
		"Your chats with the team; they count toward the daily limit.",
	costsHowWell: "How well the team works",
	costsWholeProject: "Across the whole project.",
	costsSprintOnly: "In sprint {n} only.",
	costsShowSprint: "Show sprint {n} only",
	metricNotYet: "Not yet: no work has been accepted",
	metricFirstTry: "Work accepted on the first try",
	metricFirstTryValue: "{first} of {accepted}",
	metricFirstTryNote: "The rest were sent back once before they passed.",
	metricNeeded: "Times the team needed you, per finished task",
	metricNeededNote: "Approvals, answers, and help when stuck.",
	metricCost: "Average cost of a finished task",
	metricChecks: "Checks Farik runs itself",
	metricChecksNote: "The others are judged by a reviewer or by you.",
	metricWeeks: "Active weeks: {n}",
	metricMessages:
		"Messages: {reaction} reactions, {reply} replies, {ceremony} from meetings, {human} from you",
	channel: "Team",
	chats: "Chats",
	chatsEveryone: "Everyone, together",
	chatsSaid: "{name}: {text}",
	chatsNone: "No messages yet. Ask {name} anything.",
	chatsGone: "{name} has left the team. Kept to read.",
	chatsPast: "Past teammates",
	chatsTitle: "Talking with {name}",
	chatsIntro:
		"{name} answers from memory and from reading the project, and changes nothing here. When work is needed, {name} suggests a request, and you decide whether to send it.",
	chatsIntroPhone:
		"{name} answers from memory and the project, and changes nothing.",
	chatsBack: "Back to Team",
	chatsNoSuch: "No such teammate",
	chatsLabel: "Message {name}",
	chatsSend: "Send",
	chatsEnterSends: "Enter sends, Shift+Enter for a new line",
	chatsTooLong:
		"A message is at most 4000 characters, and this one is {length}.",
	chatsSuggests: "A request {name} suggests. Change the words if you like.",
	chatsSuggested: "A request {name} suggested",
	chatsSendRequest: "Send as a request",
	chatsNothingSent: "Nothing is sent until you press it.",
	chatsSentAs: "Sent as {id}",
	chatsAnswering: "{name} is thinking…",
	chatsDaySpent:
		"Today’s spending limit is reached, so {name} will answer tomorrow. Your message is kept.",
	chatsDaySpentLink: "See today’s costs",
	chatsAsleep:
		"{name} is resting until {time}, when the AI account’s usage limit resets, and will answer then.",
	chatsKeyRefused: "{name} cannot answer: your AI provider refused the key.",
	chatsKeyLink: "Check the key in Settings",
	chatsNoAnswer: "{name} could not answer. Ask again.",
	chatsRetired: "{name} has left the team. This chat is kept for you to read.",
	channelIntro:
		"Where the team talks. Nothing said here starts work: to ask for something, use the request box on Today.",
	channelMessages: "Messages",
	channelYou: "You",
	channelWhy: "Why: {reason}",
	channelAtYou: "@you",
	channelThread: "{thread}, {weekday}: {n} people posted",
	channelThreadOne: "{thread}, {weekday}: 1 person posted",
	channelShow: "Show",
	channelHide: "Hide",
	channelReplyingTo: "Replying to {name}",
	channelWaitingOnYou: "waiting on you",
	channelPostLabel: "Post to the team",
	channelPostPhone: "Message the team",
	channelPlaceholder: "Type @ to mention someone",
	channelPost: "Post",
	channelHintLead: "A mentioned agent answers here. To have work done,",
	channelHintLink: "send a request",
	channelHintEnd: "instead.",
	channelTooLong:
		"A message is at most 2000 characters, and this one is {length}.",
	channelMentionList: "People to mention",
	channelMentionCount:
		"People to mention: {n}. Use the arrow keys, then Enter.",
	channelMeetings: "Meetings in this sprint",
	channelMeetingLink: "{thread}, {weekday}",
	channelMeetingGone: "That meeting is older than the channel keeps.",
	channelEarlier: "Show earlier messages",
	channelEarlierFailed:
		"Farik could not read the earlier messages. Try again in a moment.",
	channelPreview: "In the channel",
	channelOpen: "Open the channel",
	sprintReadIt: "Read it",
	previewTitle: "How to open your app",
	previewLead:
		"{designer}, your UI/UX Designer, looks at your app in a browser to check its screens. Tell Farik the commands you use to open it. Farik runs them inside Docker’s sandbox, never straight on your computer.",
	previewSetupTitle: "{designer} needs to know how to open your app",
	previewSetupLead:
		"{designer} looks at your app in a browser. Tell Farik the commands you use to open it; Farik runs them inside Docker’s sandbox. Not sure? Leave them empty. You can add them in Settings later, and {designer} waits until you do.",
	previewPrepare: "Get it ready (optional)",
	previewPrepareHint:
		"Installs what your app needs and builds it. This may use the internet, for up to 15 minutes.",
	previewStart: "Start it",
	previewStartHint: "Starts your app. The internet is off while it runs.",
	previewPort: "Port",
	previewPortHint: "The number your app answers on.",
	previewPath: "First page",
	previewPathHint: "The page {designer} opens first.",
	previewNotSure:
		"Not sure what to type? Whoever set up your app knows. Your README file often says too.",
	refusePreviewPort: "Use a number from 1024 to 65535.",
	refusePreview:
		"Farik cannot use these. Starting your app needs a command and a port, each command is at most 500 characters, and the first page starts with /.",
	teamNeedsSandbox: "Needs Docker’s sandbox",
	teamNeedsSandboxNote:
		"{designer} opens your app in a browser, and only inside Docker’s sandbox, a safe box that keeps it away from the rest of your computer. Farik did not find Docker here.",
	teamCheckAgain: "Check again",
	teamInstallDocker: "How to install Docker",
	connectors: "Connectors",
	connectorsLead: "let {name} use outside tools",
	connectorPlaywright: "Playwright",
	connectorPlaywrightNote:
		"Comes with Farik. Opens your app in a browser inside Docker’s sandbox, so {name} can see its screens as a customer would. It reaches only your app, nothing else on the internet.",
	connectorOff:
		"Without it {name} cannot look at your app, so Farik gives {name} no work.",
	connectorsNote:
		"On for a UI/UX Designer. You can turn it on for anyone else.",
	connectorsYours: "Added by you",
	connectorsYoursLead:
		"connectors Farik has not checked; you labelled their tools",
	connectorStdio: "Started by a command on this computer",
	connectorHttp: "Reached at a web address",
	connectorTools: "{count} tools: {labels}",
	connectorOneTool: "1 tool: {labels}",
	connectorCantUse: "{count} Farik can’t use",
	connectorAgain: "Connect again to use it",
	connectorAgainNote:
		"Its settings in your project changed since you connected it on this computer, for example in a copied project or a saved team. {name} does not use it until you check it and connect again.",
	connectorAgainButton: "Connect again",
	connectorUnreadable: "Farik cannot read {name}’s keys for {server} right now",
	connectorUnreadableNote:
		"The last time Farik looked, your computer’s keychain or the private file that keeps them could not be opened, so {name} works without {server} for now. If your computer asks whether Farik may use the keychain, choose “Always”.",
	connectorRemove: "Remove",
	connectorRemoveLabel: "Remove {server}",
	connectorRemoveTitle: "Remove {server} from {name}?",
	connectorRemoveBody:
		"{name} stops using {server} from the next piece of work. Farik deletes the keys you gave it for {name} from this computer.",
	connectorRemoveBodyKeychain:
		"{name} stops using {server} from the next piece of work. Farik deletes the keys you gave it for {name} from your keychain.",
	connectorRemoveBodyFile:
		"{name} stops using {server} from the next piece of work. Farik deletes the keys you gave it for {name} from the private file on this computer.",
	connectorKeychain: "{name}’s keys are in your keychain.",
	connectorFile: "{name}’s keys are in a private file on this computer.",
	connectorRemoveOthers:
		"Nobody else on the team is affected. To use it again, add it again and type the keys.",
	connectorKeep: "Keep it",
	connectorCustom: "A custom connector",
	connectorCustomNote:
		"Any connector, by the command that starts it or its web address. Farik has not checked it, so you label each of its tools yourself. A connector started by a command runs on this computer with your rights, so add only one you trust. It runs in a folder Farik keeps for it, so give a file of yours by its full path, starting with /.",
	connectorCustomAdd: "Add a custom connector",
	connectorCustomKeychain:
		"If your computer asks whether Farik may use the keychain, choose “Always”, or the connector cannot start.",
	tagNetwork: "Only reads",
	tagNetworkNote:
		"{name} may use it any time. It looks things up and changes nothing.",
	tagExternal: "Changes things, asks you",
	tagExternalNote:
		"{name} asks you before each use, and you see exactly what {name} wants to send.",
	tagDenied: "Never",
	tagDeniedNote: "{name} is not given it.",
	addTitle: "Add a custom connector to {name}",
	addTitleNamed: "Add {server} to {name}",
	addStepStart: "How to start it",
	addStepLabel: "Label its tools",
	addStepDone: "Done",
	addName: "Name",
	addNameHint:
		"Lowercase letters, numbers and dashes. It is how {name}’s page lists it.",
	addHow: "How does it start?",
	addCommandChoice: "A command",
	addCommandChoiceNote: "Farik runs it on this computer.",
	addUrlChoice: "A web address",
	addUrlChoiceNote: "The service runs it for you.",
	addCommand: "Command",
	addCommandHint:
		"The program the connector’s instructions start with, like npx, or its full path, starting with /. It runs on this computer with your rights, so use only one you trust.",
	addArgs: "What comes after it",
	addArgsHint:
		"Copy each part that follows the program in the connector’s instructions into a field of its own, without quotes.",
	addArg: "Part {count}",
	addArgRemoveLabel: "part {count}",
	addArgMore: "Add a part",
	addUrl: "Web address",
	addUrlHint: "Copy it from the service’s instructions.",
	addUrlSecret:
		"This address has a key inside it. Farik cannot keep a key that is part of an address safe yet, so a service like this cannot be added for now. Zapier is one.",
	addHeader: "Where the key goes",
	addHeaderHint: "Change it only if the service’s instructions say so.",
	addHeaderN: "Header {count}",
	addHeaderRemoveLabel: "header {count}",
	addHeaderMore: "Add a header",
	addHeaderTwice:
		"Another header above has this name. Give each header its own name, or remove one.",
	addKeys: "Keys",
	addKeysHint:
		"Each key is for {name} only. Name it as the connector’s instructions do.",
	addKeysAgain:
		"Type {name}’s key again. Farik does not reuse the old one for a changed connector.",
	addKeyName: "Key name",
	addKeyValue: "Key",
	addKeyRemove: "Remove",
	addKeyRemoveLabel: "key {count}",
	addKeyMore: "Add another key",
	addNext: "Next: list its tools",
	addNextNote:
		"Farik starts it once, with {name}’s keys, to list what it can do.",
	addChanged:
		"{server}’s settings in your project changed since you connected it on this computer, or it was never connected here. Check each one against the service’s or the connector’s instructions before you go on.",
	addListLead:
		"Farik has not checked {server}, so you decide what {name} may do with each of its {count} tools. When unsure, leave “Changes things, asks you”.",
	addFrom: "Each tool’s description comes from {server}.",
	addUnusable:
		"Farik can’t use this tool: its name has characters Farik can’t pass on. {name} is not given it.",
	addBack: "Back",
	addDone: "{server} is added to {name}",
	addKeychain:
		"{name}’s keys for {server} are kept in your computer’s keychain.",
	addKeychainNote:
		"{name} never sees them: Farik hands them to {server} when {server} starts.",
	addFile:
		"{name}’s keys for {server} are kept in a private file only you can read.",
	addFileNote:
		"This computer has no keychain, so Farik keeps them in a file in your Farik folder that only your user account can open. {name} never sees them.",
	addKeychainNoteNoSandbox:
		"Farik hands them to {server} when {server} starts, and never puts them in {name}’s instructions. Without Docker’s sandbox, a command {name} runs on this computer could reach them.",
	addFileNoteNoSandbox:
		"This computer has no keychain, so Farik keeps them in a file in your Farik folder that only your user account can open. Without Docker’s sandbox, a command {name} runs on this computer could reach them.",
	addNextWork: "{name} can use it from the next piece of work.",
	addOnly:
		"Only {name} has {server}. To give it to someone else, add it from their page, with their own key.",
	addBackTo: "Back to {name}",
	addNameWrong:
		"Use lowercase letters, numbers and dashes, starting with a letter.",
	addNameReserved: "Farik keeps this name for itself. Choose another.",
	addNameTwice: "{name} already has a connector with this name.",
	addCommandWrong:
		"Farik cannot use this command as it is. Copy it again from the connector’s instructions.",
	addUrlWrong:
		"Farik cannot use this address. Copy it again from the service’s instructions; it starts with https://.",
	addHeaderWrong:
		"Write a name, a colon, then the value, like Authorization: Bearer {API_KEY}, naming only the keys below.",
	addCommandNotAbsolute:
		"Farik cannot find a program by a path like this one. Give the program’s name alone, like npx, or its full path, starting with /.",
	addCommandWhole:
		"Put only the program here, like npx. Put each part after it below, in a field of its own.",
	addStateInsideProject:
		"Farik keeps its settings inside this project’s folder, so a connector here would run among the project’s files. Whoever set up Farik on this computer can keep its settings elsewhere.",
	addArgSecret:
		"This puts a key itself in your project’s shared settings. Leave it out here, and type the key under Keys, named as the connector’s instructions name it.",
	addHeaderSecret:
		"This puts the key itself in your project’s shared settings. Write {API_KEY} where the key goes, and type the key under Keys.",
	addTagUnknown:
		"{server}’s tools changed since Farik listed them. Press “Next: list its tools” to list them again, then label each one.",
	addKeyWrong:
		"A key name is capital letters, numbers and underscores, starting with a letter, like API_KEY. Up to 8 keys.",
	addNotListed:
		"Farik could not start {server} or reach it to list its tools. Check the command or the address, and the keys, against its instructions.",
	addTimeout:
		"{server} did not answer within thirty seconds. Check the command or the address, and try again.",
	uiPathsTitle: "Which files are screens",
	uiPathsLead:
		"When a Developer’s change touches a file like these, the UI/UX Designer checks its screens before the Architect reviews the code.",
	uiPathsAdd: "Add a file pattern",
	uiPathsAddButton: "Add",
	uiPathsRemove: "Remove",
	designChecked: "{name}, your UI/UX Designer, checked the screens first",
	designPassed: "Passed, and sent on to {reviewer}",
	designFailed: "Sent back to {builder}",
	designBackOnce: "{name} sent it back once, on {day}",
	designBackMany: "{name} sent it back {n} times, last on {day}",
	designBackThen: "{builder} changed it, and the next look passed.",
	designChecksTitle: "The four checks",
	designChecksLead:
		"Farik took each picture and ran the accessibility check itself, against WCAG 2.2 AA, the usual standard for pages everyone can use.",
	shotPhone: "Phone",
	shotComputer: "Computer",
	shotLight: "light",
	shotDark: "dark",
	shotAlt: "{width}, {theme}",
	shotCaption: "{width}, {theme} theme",
	shotPhoneWide: "360 pixels wide",
	shotComputerWide: "1280 pixels wide",
	shotClean: "No problems found",
	shotViolation: "{rule}, {impact}",
	designChecking: "Checking the screens",
	designCheckingNote:
		"{designer} is looking at it on a phone and a computer, in the light and dark themes. {reviewer} reviews the code once {designer} passes it.",
	designOnDesigner: "Waiting on the Designer",
	designOnDesignerNote:
		"{developer} changed a screen, and {designer} checks every screen before {reviewer} sees it. {designer} is paused.",
	designResume: "Resume {designer} on the Team page",
	designNoBrowser: "The Designer’s browser is off",
	designNoBrowserNote:
		"{developer} changed a screen, and {designer} checks every screen before {reviewer} sees it. {designer}’s browser is off.",
	designTurnOnBrowser: "Turn Playwright on for {designer} on the Team page",
	designerWorks: "How {designer} works",
	designerStepLook: "Looks at your app in a browser",
	designerStepPlan: "Writes a plan",
	designerStepApprove: "{pm} approves the plan",
	designerStepChange: "{designer} changes the page",
	designerStepReview: "{reviewer} reviews it, as for any task",
	stepDone: "Done",
	stepNow: "Now",
	plansSentBack: "Plans sent back",
	plansOf: "{n} of {of}",
	waitingPreviewMissing: "Tell Farik how to open your app",
	waitingPreviewMissingLine:
		"{designer} needs it to look at your screens. Until then {designer} takes no work, and nobody checks the screens {developer} builds.",
	waitingOpenSettings: "Open Settings",
	waitingNeedsSandbox: "{agent} needs Docker’s sandbox",
	waitingNeedsSandboxLine:
		"The UI/UX Designer needs Docker’s sandbox to open your app. Turn the sandbox on, or retire the Designer.",
	waitingOpenTeam: "Open the Team page",
	waitingNeedsBrowser: "{agent}’s browser is off",
	waitingNeedsBrowserLine:
		"{designer} opens your app with Playwright. Turn Playwright on for {designer} on the Team page; until then {designer} takes no work, and nobody checks the screens {developer} builds.",
	startsLegend:
		"Start from the team Farik suggests, from a team you saved in another project, or from nothing. Whichever you pick, you can change anyone below.",
	startSuggested: "The suggested team",
	startSuggestedNote:
		"Six people, one for each job. A good start for a first project.",
	startSaved: "A saved team",
	startSavedNote:
		"A team you tuned before and saved from a Team page. It brings everyone’s name, picture, persona and model, and your answers to the setup questions.",
	startSavedNone:
		"You have no saved teams yet. Save one from a project’s Team page with “Save as a template”.",
	startWhich: "Which saved team?",
	startScratch: "From scratch",
	startScratchNote:
		"Start with the two every team needs, a Product Manager and a Developer, and add whoever else you want.",
	teamLeadSaved:
		"Filled from {name}. Change anyone before you continue; the saved team itself stays as it is.",
	teamLeadScratch:
		"Every team needs a Product Manager to plan and a Developer to build. Name them, then add whoever else you want.",
	teamScratchNote:
		"Every team needs one. Picture, persona and model are the role’s own; change them later on the Team page.",
	teamNameBoth: "Name both to continue.",
	teamSavedAnswers:
		"{name} also holds your answers about what they may do, spending, finishing work and checking plans. You will see them on the next screens, already chosen.",
	templateMeta: "{names} · saved {date}",
	finishLeadSaved:
		"Accepted work has to be added to your project. {name}’s answer is already chosen; change it if this project needs another.",
	finishCarried: "What they may do, from {name}",
	finishCommands: "Run commands on this computer",
	finishPush: "Send work to your online repository",
	finishYes: "Yes.",
	finishNo: "No.",
	finishCommandsYes:
		"The team may run commands, in a sealed box away from your other files.",
	finishCommandsNo:
		"Nobody runs commands; Farik still runs every check itself.",
	finishPushYes: "The Developer may send work to its own branches online.",
	finishPushNo: "Everything stays on this computer.",
	finishCarriedBefore:
		"You answered these when you saved the team, so Farik does not ask again. Change them any time in ",
	finishCarriedAfter: ", under Your team’s rules.",
	templateSaveOpen: "Save as a template",
	templateUseOpen: "Use a saved team",
	saveTitle: "Save this team as a template",
	saveLead:
		"Farik keeps a copy on this computer, so any of your projects can start from it.",
	saveKeeps: "What it keeps",
	saveKeepsBody:
		"Everyone’s name, picture, persona and model, and your answers about what they may do, checking plans, spending and finishing work.",
	saveStays: "What stays with this project",
	saveStaysBody:
		"The team’s rules, the checks, how to open your app, and who is paused or retired.",
	saveName: "Name",
	saveNameHint: "Up to 60 characters, such as “My usual team”.",
	saveSave: "Save",
	saveReplace: "Replace",
	savedAsBefore: "Saved as ",
	savedAsAfter:
		". Any project on this computer can use it, and you can rename or delete it in ",
	templateExists:
		"A saved team is called {name} already. Replace it, or choose another name.",
	templateRenameTaken:
		"A saved team is called {name} already. Choose another name.",
	templateName: "Give the saved team a name with a letter or a number in it.",
	templateUnreadable:
		"This saved team cannot be read. Delete it, or fix the file by hand.",
	templateNoFolder:
		"Farik has no folder on this computer to keep saved teams in.",
	templateChanged:
		"This saved team was saved again since you looked at it. Go back and look at what changes once more.",
	useLead:
		"Pick a team you saved. Farik shows you who stays, who joins and who leaves before anything changes.",
	useList: "Saved teams",
	useSettingsBefore: "Rename or delete saved teams in ",
	useShow: "Show what changes",
	usePreviewTitle: "Use {name}?",
	usePreviewLead:
		"This is what your team would look like. Nothing changes until you choose “Use this team”.",
	useStays: "Stays",
	useStaysNote:
		"Keep their work and chats, and take the saved name, picture, persona and model.",
	useJoins: "Joins",
	useJoinsNote: "New to this project.",
	useRetired: "Retired",
	useRetiredNote:
		"Have done work here, so they leave the team and their work and chats stay to read.",
	useRemoved: "Removed",
	useRemovedNote: "Never started any work here, so they are taken off.",
	useNobody: "Nobody",
	useChanges: "What changes",
	useApply: "Use this team",
	useCannot: "Farik cannot use this team here",
	useNothingChanged: "Nothing has changed.",
	usePaused: "{role} · paused",
	templateNoActive: "Your team would have no active {role}.",
	templatePaused: "{paused} stays but is paused.",
	templatePausedRetired:
		"{paused} stays but is paused, and {retired} would be retired.",
	templateResume:
		"Resume {paused} on the Team page first, or choose another saved team.",
	templateChooseAnother: "Choose another saved team.",
	savedTeams: "Saved teams",
	savedTeamsLead:
		"Teams you saved from a Team page. Every project on this computer can start from them. Renaming or deleting one changes no project’s team.",
	savedTeamsNoneBefore: "You have no saved teams yet. Save one from your ",
	savedTeamsNoneAfter: " page with “Save as a template”.",
	savedRename: "Rename",
	savedRenameLabel: "New name for {name}",
	savedRenameSave: "Save name",
	savedDelete: "Delete",
	savedDeleteAsk: "Delete {name}?",
	savedDeleteNote:
		"Projects that started from it keep their teams. This cannot be undone.",
	savedDeleteYes: "Delete it",
	savedDeleteNo: "Keep it",
	savedFolder: "Kept on this computer, in {folder}.",
};
